#!/bin/bash

dir_name="Software"
install_path="$HOME/$dir_name"
bashrc_path="$HOME/.bashrc"

test -d $install_path
if [[ $? == "1" ]]; then
  mkdir $install_path
fi

ln python/git_puller.py $install_path
ln shell-scripts/create_code_file $install_path

echo "" >> $bashrc_path
echo "alias git_puller='python $install_path/git_puller.py'" >> $bashrc_path
echo "alias create_code_file='$install_path/./create_code_file'" >> $bashrc_path

source $bashrc_path
