#!/bin/bash

dir_name="Software"

test -d $HOME/$dir_name
if [[ $? == "1" ]]; then
  mkdir $HOME/$dir_name
fi

install_path="$HOME/$dir_name"
bashrc_path="$HOME/.bashrc"

ln python/git_puller.py $install_path
ln shell-scripts/create_code_file $install_path

echo "alias git_puller='python $install_path/git_puller.py'" >> $bashrc_path
echo "alias create_code_file='$install_path/./create_code_file'" >> $bashrc_path

source $bashrc_path
