io.write("Enter the first number: ")
io.flush()
local a = tonumber(io.read())
io.write("Enter the second number: ")
io.flush()
local b = tonumber(io.read())

print(string.format("%g+%g=%g", a, b, a + b))
print(string.format("%g-%g=%g", a, b, a - b))
print(string.format("%g*%g=%g", a, b, a * b))
print(string.format("%g/%g=%g", a, b, a / b))
