#!/bin/bash

if [[ $1 == "" ]]; then
  read -e -p "Enter filename: " file_name
elif [[ $1 != "" ]]; then
  file_name=$1
fi

file_name="$file_name.sh"

echo "#!/bin/bash

# code" > $file_name

chmod +x $file_name
echo "File created."
