#!/bin/bash

create_sh_file() {
  echo "#!/bin/bash

# code" > $2.$1

  chmod +x $2.$1
}

create_c_file() {
  echo "#include <stdio.h>

int main() {
  /* code */
  return 0;
}" > $2.$1
}

create_cpp_file() {
  echo "#include <iostream>
using namespace std;

int main() {
  /* code */
  return 0;
}" > $2.$1
}

create_d_file() {
  echo "import std.stdio;

void main() {
  /* code */
}" > $2.$1
}

create_java_file() {
  class_name=$(echo $2 | awk -F "/" '{print $NF}')

  echo "public class $class_name {
  public static void main(String[] args) {
    /* code */
  }
}" > $2.$1
}

create_html_file() {
  echo "<!DOCTYPE html>
<html>
  <head>
    <meta charset=\"utf-8\">
    <title></title>
  </head>
  <body>
  </body>
</html>" > $2.$1
}

if [[ $1 == "" || $2 == "" ]]; then
  echo "create_code_file [sh|c|cpp|d|java|html] [filename]"
elif [[ $1 != "" && $2 != "" ]]; then
  case $1 in
    sh) create_sh_file $@;;
    c) create_c_file $@;;
    cpp) create_cpp_file $@;;
    d) create_d_file $@;;
    java) create_java_file $@;;
    html) create_html_file $@;;
  esac
  echo "File created."
fi
