#!/bin/bash

a=$(date +"%Y")
b=$(($a-7))
c=$(($a+7))

for (( i=$b; i<=$c; i++ )); do
  if [[ $i<$a ]]; then
    d=`ncal -o $i`
    echo "В $i году Пасха была: $d"
  elif [[ $i>$a ]]; then
    d=`ncal -o $i`
    echo "В $i году Пасха будет: $d"
  elif [[ $i==$a ]]; then
    d=`ncal -o $i`
    e=$(date +"%d.%m.%Y")
    if [[ $d>$e ]]; then
      echo "В $i году Пасха будет: $d (этот год)"
    elif [[ $d<$e ]]; then
      echo "В $i году Пасха была: $d (этот год)"
    else
      echo "Something is wrong!"
    fi
  else
    echo "Something is wrong!"
  fi
done
