#!/bin/bash

gem_config="~/.gemrc"
ruby_env_config="~/.bashrc"

echo "Your Linux distro:"
echo "1 - Ubuntu/Linux Mint"
echo "2 - Arch Linux"
read -p "-> " distro

if [[ $distro == "1" ]]; then
  sudo apt update
  sudo apt install ruby-full build-essential zlib1g-dev

  echo 'gem: --no-user-install' > $gem_config
  echo 'export GEM_HOME="$HOME/.gem"' >> $ruby_env_config
  echo 'export PATH="$PATH:$GEM_HOME/bin"' >> $ruby_env_config
  source $ruby_env_config

  gem install jekyll bundler

  jekyll new myblog
  cd myblog
  bundle exec jekyll serve

  bundle update
elif [[ $distro == "2" ]]; then
  sudo pacman -Syy
  sudo pacman -S ruby

  echo 'gem: --no-user-install' > $gem_config
  echo 'export GEM_HOME="$HOME/.gem"' >> $ruby_env_config
  echo 'export PATH="$PATH:$GEM_HOME/bin"' >> $ruby_env_config
  source $ruby_env_config

  gem update
  gem install jekyll bundler

  jekyll new myblog
  cd myblog
  bundle exec jekyll serve

  bundle update
else
  echo "Something is wrong!"
fi
