name: C++

on:
  push:
    branches:
      - master

jobs:
  win:
    name: Windows (windows-latest)
    runs-on: windows-latest
    steps:
      - name: Git Clone
        uses: actions/checkout@v2

      - name: Build
        run: |
          cd cpp
          make

      - name: Upload artifact (calc.cpp)
        uses: actions/upload-artifact@v1
        with:
          name: calc_cpp_win
          path: cpp\calc_cpp_win

      - name: Upload artifact (num_systems.cpp)
        uses: actions/upload-artifact@v1
        with:
          name: num_systems_cpp_win
          path: cpp\num_systems_cpp_win

  linux:
    name: Linux (ubuntu-latest)
    runs-on: ubuntu-latest
    steps:
      - name: Git Clone
        uses: actions/checkout@v2

      - name: Build
        run: |
          cd cpp
          make

      - name: Upload artifact (calc.cpp)
        uses: actions/upload-artifact@v1
        with:
          name: calc_cpp_linux
          path: cpp/calc_cpp_linux

      - name: Upload artifact (git_puller.cpp)
        uses: actions/upload-artifact@v1
        with:
          name: git_puller_cpp_linux
          path: cpp/git_puller_cpp_linux

      - name: Upload artifact (num_systems.cpp)
        uses: actions/upload-artifact@v1
        with:
          name: num_systems_cpp_linux
          path: cpp/num_systems_cpp_linux
